
#desafio CI - Install, Test, Push...
steps:

- id: 'Install soma'
  name: 'gcr.io/cloud-builders/go'
  args: ['install', 'soma']
#  args: ['install', '.']
  env: ['GOPATH=.']
#  env: ['PROJECT_ROOT=soma']


- id: 'Test soma'
  name: 'gcr.io/cloud-builders/go'
  args: ['test', '-v','soma']
  env: ['GOPATH=.']
#  env: ['PROJECT_ROOT=soma']


- id: 'Build imagem soma e push'
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/soma', '.']

images: ['gcr.io/$PROJECT_ID/soma']

